language: go
go:
  - 1.4
  - tip
env:
  - "PATH=/home/travis/gopath/bin:$PATH"
before_install:
  - go get github.com/mitchellh/gox
  - go get github.com/tcnksm/ghr
after_success:
  - gox -output "dist/{.OS}_{.Arch}_{.Dir}"
  - ghr --username uetchy --token $GITHUB_TOKEN --replace --prerelease --debug pre-release dist/
