sudo: false
language: go
go:
  - tip
before_install:
  - go get -v github.com/mitchellh/gox
before_deploy:
  - gox -os="linux darwin windows" -arch="386 amd64" -output "pkg/{{.Dir}}_{{.OS}}_{{.Arch}}" -ldflags="-X main.Version=`git describe --tags --match 'v*'`" # Cross compile go project
  - ./pkg/nv_linux_amd64 --version # Verify compiled binaries
deploy: # Deploy stable version if commmits have a tag such as 'v2.0.0'
  provider: releases
  api_key: $GITHUB_TOKEN
  file: "pkg/*"
  skip_cleanup: true
  on:
    tags: true
