language: go
go:
  - 1.5
  - tip
before_install:
  - go get github.com/laher/goxc
  - go get github.com/tcnksm/ghr
  - go get github.com/golang/lint/golint
script:
  - golint
after_success:
  # Always release compiled build for 'pre-release' tag
  - goxc -d . -tasks='xc archive' -bc 'linux,!arm windows darwin' -build-ldflags "-X main.Version=$(git describe --tags --always)"
  - ghr --username uetchy --token $GITHUB_TOKEN --replace --prerelease pre-release snapshot/
  - ./snapshot/linux_amd64/gst --version
deploy:
  # Release if any 'vX.X.X' tag given
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - snapshot/gst_darwin_386.zip
    - snapshot/gst_darwin_amd64.zip
    - snapshot/gst_linux_386.tar.gz
    - snapshot/gst_linux_amd64.tar.gz
    - snapshot/gst_windows_386.zip
    - snapshot/gst_windows_amd64.zip
  skip_cleanup: true
  on:
    tags: true
